<?php

namespace ContainerKUrpvcs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2A0r227Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2A0r227' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2A0r227'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mediaRepository' => ['privates', 'App\\Repository\\MediaRepository', 'getMediaRepositoryService', true],
            'product' => ['privates', '.errored..service_locator.2A0r227.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.2A0r227": it references class "App\\Entity\\Product" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'mediaRepository' => 'App\\Repository\\MediaRepository',
            'product' => 'App\\Entity\\Product',
        ]);
    }
}
