<?php

namespace ContainerKUrpvcs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ErszJfIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ErszJfI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ErszJfI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commandLineRepository' => ['privates', 'App\\Repository\\CommandLineRepository', 'getCommandLineRepositoryService', true],
        ], [
            'commandLineRepository' => 'App\\Repository\\CommandLineRepository',
        ]);
    }
}
