<?php

namespace ContainerKUrpvcs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerAddress2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ohuPNgu.App\Entity\CustomerAddress' shared service.
     *
     * @return \App\Entity\CustomerAddress
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ohuPNgu": it references class "App\\Entity\\CustomerAddress" but no such service exists.');
    }
}
