<?php

namespace ContainerKUrpvcs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandLine2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.XDeVOhK.App\Entity\CommandLine' shared service.
     *
     * @return \App\Entity\CommandLine
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.XDeVOhK": it references class "App\\Entity\\CommandLine" but no such service exists.');
    }
}
