index:
    path: /
    controller: App\Controller\ProductController::index
user:
    path: /user/
    controller: App\Controller\UserController::index
customeraddress:
    path: /customeraddress/
    controller: App\Form\CustomerAddressType.php
carnet:
    path: /carnet
    controller: App\Controller\ProductController::category
papeterie:
    path: /papeterie
    controller: App\Controller\ProductController::category
autres:
    path: /autres
    controller: App\Controller\ProductController::category
login:
    path: /login
    controller: App\Controller\SecurityController::login
register:
    path: /register
    controller: App\Controller\RegistrationController::register
category_index:
    path: /category
    controller: App\Controller\CategoryController::index
categorie:
    path: /categorie
    controller: App\Controller\CategoryController::categorie

product_add:
    path: /addProduct
    controller: App\Controller\ProductController::product_add
recap:
    path: /recap
    controller: App\Controller\OrderController::recap
customer_address_new:
    path: /new
    controller: App\Controller\CustomerAddressController::new