<?php

namespace ContainerHdrtMyk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kdnloe4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Kdnloe4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Kdnloe4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'medium' => ['privates', '.errored..service_locator.Kdnloe4.App\\Entity\\Media', NULL, 'Cannot autowire service ".service_locator.Kdnloe4": it references class "App\\Entity\\Media" but no such service exists.'],
        ], [
            'medium' => 'App\\Entity\\Media',
        ]);
    }
}
