<?php

namespace ContainerHdrtMyk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B6Ejh2CService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B6Ejh2C' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.B6Ejh2C'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'UsersRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'UsersRepository' => 'App\\Repository\\UsersRepository',
        ]);
    }
}
