<?php

namespace ContainerHdrtMyk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MyBYVSQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MyBYVSQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MyBYVSQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commandLine' => ['privates', '.errored..service_locator.MyBYVSQ.App\\Entity\\CommandLine', NULL, 'Cannot autowire service ".service_locator.MyBYVSQ": it references class "App\\Entity\\CommandLine" but no such service exists.'],
        ], [
            'commandLine' => 'App\\Entity\\CommandLine',
        ]);
    }
}
