<?php

namespace ContainerHdrtMyk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UzPCL5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UzPC_L5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UzPC_L5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mediaRepository' => ['privates', '.errored.w2WUnae', NULL, 'Cannot determine controller argument for "App\\Controller\\ProductController::delete()": the $mediaRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\MediaRepository". Did you forget to add a use statement?'],
            'product' => ['privates', '.errored..service_locator.UzPC_L5.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.UzPC_L5": it references class "App\\Entity\\Product" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'mediaRepository' => '?',
            'product' => 'App\\Entity\\Product',
        ]);
    }
}
