<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKUrpvcs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKUrpvcs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKUrpvcs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKUrpvcs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKUrpvcs\App_KernelDevDebugContainer([
    'container.build_hash' => 'KUrpvcs',
    'container.build_id' => 'a8802501',
    'container.build_time' => 1647196357,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKUrpvcs');
